[project]
name = "mcp-hub"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "fastmcp>=2.13.0",
  "httpx>=0.28.0",
  "python-dotenv>=1.0.0",
  "fastapi>=0.95.0",
  "uvicorn[standard]>=0.22.0"
]

[project.scripts]
mcp-hub = "hub_server:main"
mcp-weather = "weather_server:main"
